<?php


namespace Modules\Frontend\Entities;


class Category extends \Modules\Backend\Entities\Category
{

    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }
}
